[graph]
targets = [
  "x86_64-unknown-linux-gnu",
]
all-features = true

[advisories]
version = 2
git-fetch-with-cli = true

[licenses]
version = 2
allow = [
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]

[licenses.private]
ignore = true

[bans]
deny = [
  { crate = "cc:=1.0.91", reason = "breaks xwin" },
  { crate = "log", deny-multiple-versions = true },
  { crate = "serde_derive:>=1.0.172,<1.0.184", reason = "bundled binaries" },
  { crate = "tracing", deny-multiple-versions = true },
]

[sources]
unknown-git = "allow"
